# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 6s",
   "iPhone 6s Plus",
   "iPhone 5",
   "iPad Pro (12.9 inch)",
   "iPad Pro (9.7 inch)",
#   "Apple TV 1080p"
 ])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
 scheme "wic"

# Where should the resulting screenshots be stored?
 output_directory "./fastlane/screenshots"

 clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
 workspace "./wic.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help

# Latest version of iOS
# ios_version '10.0'
